runtime_dir_config.php.distenv: %env%
root_dir: %root_dir%
cache_dir: %runtime_dir%/cache/%env%

twig.options:
  cache: %runtime_dir%/cache/%env%/twig
twig.form.templates:
  - "@DominikzoggEnergyCalculator/form.html.twig"

http_cache.cache_dir: %runtime_dir%/cache/%env%/httpcache

security.firewalls:
  unsecured:
    anonymous: true

session.storage.options:
    gc_probability: 0

monolog.logfile: %runtime_dir%/log/%env%.log

orm.proxies_dir: %runtime_dir%/cache/%env%/doctrine/proxies

profiler.cache_dir: %runtime_dir%/cache/%env%/profiler

assetic.asset.root: %root_dir%
assetic.asset.asset_root: %root_dir%/web/assets
assetic_asset_path: assets

route_controller_cache: %runtime_dir%/cache/%env%/controller

console.cache: %runtime_dir%/cache/%env%/console

translation_cache: %runtime_dir%/cache/%env%/translation

knp_menu.default_renderer: twig
knp_menu.template: "@DominikzoggEnergyCalculator/menu.html.twig"

knp_paginator.options:
  subscriberOptions:
    defaultPaginationTemplate: "@SaxulumPaginationProvider/twitter_bootstrap_v3_pagination.html.twig"
    defaultPageRange: 3
