---
- name: Nginx | add key
  apt_key: keyserver=keys.gnupg.net id=E9C74FEEA2098A6E

- name: Nginx | app repository
  apt_repository: repo='deb http://dotdeb.netmirror.org jessie all' state=present

- name: Nginx | app src repository
  apt_repository: repo='deb-src http://dotdeb.netmirror.org jessie all' state=present

- name: Nginx | install needed modules
  apt: name={{ item }} state=present
  with_items:
    - nginx-full

- name: Nginx | ssl private key
  template:
    src=key.j2
    dest=/etc/nginx/key

- name: Nginx | ssl certificate
  template:
    src=cert.j2
    dest=/etc/nginx/cert

- name: Nginx | nginx.conf
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx